version: "2"

services:
    cypress:
        build: "."
        container_name: cypress
        ports:
            - 80:80

        environment:
            - DEBUG=True
            - HOST=0.0.0.0
            - PORT=80
            - SECRET_KEY=anylongtext
            # min
            - SESSION_LIFETIME=1440

            - LDAP_HOST=xxx.xxx.xxx.xxx
            - LDAP_BASE_DN=dc=example,dc=co,dc=jp
            - LDAP_USER_DN=ou=people
            - LDAP_USER_RDN_ATTR=uid
